# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("quiz", "0002_auto_20180214_1720")]

    operations = [
        migrations.AlterField(
            model_name="questionstat",
            name="candidate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questionstat",
                to="accounts.UserProfile",
            ),
        )
    ]
