# Generated by Django 2.0.2 on 2018-02-17 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("quiz", "0004_auto_20180217_1608")]

    operations = [
        migrations.AlterField(
            model_name="teststat",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teststats",
                to="accounts.UserProfile",
            ),
        )
    ]
