# Generated by Django 2.0.2 on 2018-02-19 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("quiz", "0005_auto_20180217_1632")]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="candidate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate_feedback",
                to="quiz.Test",
            ),
        )
    ]
