# Generated by Django 2.0.2 on 2018-02-19 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("quiz", "0007_auto_20180219_1204")]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate_feedback",
                to="accounts.UserProfile",
            ),
        )
    ]
