# Generated by Django 2.0.2 on 2018-02-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20180219_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='published_on',
            field=models.DateTimeField(null=True),
        ),
    ]
