# Generated by Django 2.0.2 on 2018-02-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("quiz", "0009_test_published_on")]

    operations = [
        migrations.AddField(
            model_name="teststat", name="score", field=models.IntegerField(null=True)
        )
    ]
