# Generated by Django 2.0.2 on 2018-03-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("quiz", "0010_teststat_score")]

    operations = [
        migrations.AlterField(
            model_name="questionstat",
            name="response",
            field=models.CharField(max_length=500, null=True),
        )
    ]
