# Generated by Django 2.0.2 on 2018-03-04 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20180304_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='negative_marking',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
