# Generated by Django 2.0.2 on 2018-03-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("quiz", "0013_auto_20180304_1752")]

    operations = [
        migrations.AlterField(
            model_name="questionstat",
            name="response",
            field=models.CharField(blank=True, default=None, max_length=500),
            preserve_default=False,
        )
    ]
