# Generated by Django 2.0.2 on 2018-06-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20180306_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='private_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
