# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topic', '__first__'),
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic_url', models.CharField(blank=True, max_length=1000)),
                ('following', models.ManyToManyField(blank=True, related_name='followed_by', to='accounts.UserProfile')),
                ('topics', models.ManyToManyField(blank=True, related_name='liked_by', to='topic.Topic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='socialaccount.SocialAccount')),
            ],
        ),
    ]
